---
- hosts: all
  tasks:
   - name: Install Maven using Ansible
     become: yes
     apt:
      name: "{{ packages }}"
      state: present
     vars:
      packages:
   - maven
   - name: Deploy static website
     copy:
       src: index.html
       dest: /var/www/html/
...
